import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "@/app/components/Header";
import Footer from "./components/Footer";
// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  variable: "--primary-font",
  display: "swap",
});

// -----roboto-font------
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  variable: "--secondary-font",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
